/* this file is generated by fft_caterpillar toolset */
#ifdef USE_AVX
	#include <immintrin.h>
#endif
#define LN_FFT  9  /* number of fft points: 1024 */
const unsigned int cat_ln = 9;
/*   */
#define W_0_02   1.000000000000000 /* angle 0.00 dg */ 
#define W_0_04   0.000000000000000 /* angle 90.00 dg */ 
#define W_0_08   0.707106781186547 /* angle 45.00 dg */ 
#define W_0_16   0.923879532511287 /* angle 22.50 dg */ 
#define W_1_16   0.382683432365090 /* angle 67.50 dg */ 
#define W_0_32   0.980785280403230 /* angle 11.25 dg */ 
#define W_1_32   0.831469612302545 /* angle 33.75 dg */ 
#define W_2_32   0.555570233019602 /* angle 56.25 dg */ 
#define W_3_32   0.195090322016128 /* angle 78.75 dg */ 
#define W_0_64   0.995184726672197 /* angle 5.62 dg */ 
#define W_1_64   0.956940335732209 /* angle 16.88 dg */ 
#define W_2_64   0.881921264348355 /* angle 28.13 dg */ 
#define W_3_64   0.773010453362737 /* angle 39.38 dg */ 
#define W_4_64   0.634393284163646 /* angle 50.62 dg */ 
#define W_5_64   0.471396736825998 /* angle 61.88 dg */ 
#define W_6_64   0.290284677254462 /* angle 73.13 dg */ 
#define W_7_64   0.098017140329560 /* angle 84.38 dg */ 
#define W_0_128   0.998795456205172 /* angle 2.81 dg */ 
#define W_1_128   0.989176509964781 /* angle 8.44 dg */ 
#define W_2_128   0.970031253194544 /* angle 14.06 dg */ 
#define W_3_128   0.941544065183021 /* angle 19.69 dg */ 
#define W_4_128   0.903989293123443 /* angle 25.31 dg */ 
#define W_5_128   0.857728610000272 /* angle 30.94 dg */ 
#define W_6_128   0.803207531480645 /* angle 36.56 dg */ 
#define W_7_128   0.740951125354959 /* angle 42.19 dg */ 
#define W_8_128   0.671558954847018 /* angle 47.81 dg */ 
#define W_9_128   0.595699304492433 /* angle 53.44 dg */ 
#define W_10_128   0.514102744193222 /* angle 59.06 dg */ 
#define W_11_128   0.427555093430282 /* angle 64.69 dg */ 
#define W_12_128   0.336889853392220 /* angle 70.31 dg */ 
#define W_13_128   0.242980179903264 /* angle 75.94 dg */ 
#define W_14_128   0.146730474455362 /* angle 81.56 dg */ 
#define W_15_128   0.049067674327418 /* angle 87.19 dg */ 
#define W_0_256   0.999698818696204 /* angle 1.41 dg */ 
#define W_1_256   0.997290456678690 /* angle 4.22 dg */ 
#define W_2_256   0.992479534598710 /* angle 7.03 dg */ 
#define W_3_256   0.985277642388941 /* angle 9.84 dg */ 
#define W_4_256   0.975702130038528 /* angle 12.66 dg */ 
#define W_5_256   0.963776065795440 /* angle 15.47 dg */ 
#define W_6_256   0.949528180593037 /* angle 18.28 dg */ 
#define W_7_256   0.932992798834739 /* angle 21.09 dg */ 
#define W_8_256   0.914209755703530 /* angle 23.91 dg */ 
#define W_9_256   0.893224301195515 /* angle 26.72 dg */ 
#define W_10_256   0.870086991108711 /* angle 29.53 dg */ 
#define W_11_256   0.844853565249707 /* angle 32.34 dg */ 
#define W_12_256   0.817584813151584 /* angle 35.16 dg */ 
#define W_13_256   0.788346427626606 /* angle 37.97 dg */ 
#define W_14_256   0.757208846506484 /* angle 40.78 dg */ 
#define W_15_256   0.724247082951467 /* angle 43.59 dg */ 
#define W_16_256   0.689540544737067 /* angle 46.41 dg */ 
#define W_17_256   0.653172842953777 /* angle 49.22 dg */ 
#define W_18_256   0.615231590580627 /* angle 52.03 dg */ 
#define W_19_256   0.575808191417845 /* angle 54.84 dg */ 
#define W_20_256   0.534997619887097 /* angle 57.66 dg */ 
#define W_21_256   0.492898192229784 /* angle 60.47 dg */ 
#define W_22_256   0.449611329654607 /* angle 63.28 dg */ 
#define W_23_256   0.405241314004990 /* angle 66.09 dg */ 
#define W_24_256   0.359895036534988 /* angle 68.91 dg */ 
#define W_25_256   0.313681740398891 /* angle 71.72 dg */ 
#define W_26_256   0.266712757474898 /* angle 74.53 dg */ 
#define W_27_256   0.219101240156870 /* angle 77.34 dg */ 
#define W_28_256   0.170961888760301 /* angle 80.16 dg */ 
#define W_29_256   0.122410675199216 /* angle 82.97 dg */ 
#define W_30_256   0.073564563599667 /* angle 85.78 dg */ 
#define W_31_256   0.024541228522912 /* angle 88.59 dg */ 
#define W_0_512   0.999924701839145 /* angle 0.70 dg */ 
#define W_1_512   0.999322384588349 /* angle 2.11 dg */ 
#define W_2_512   0.998118112900149 /* angle 3.52 dg */ 
#define W_3_512   0.996312612182778 /* angle 4.92 dg */ 
#define W_4_512   0.993906970002356 /* angle 6.33 dg */ 
#define W_5_512   0.990902635427780 /* angle 7.73 dg */ 
#define W_6_512   0.987301418157858 /* angle 9.14 dg */ 
#define W_7_512   0.983105487431216 /* angle 10.55 dg */ 
#define W_8_512   0.978317370719628 /* angle 11.95 dg */ 
#define W_9_512   0.972939952205560 /* angle 13.36 dg */ 
#define W_10_512   0.966976471044852 /* angle 14.77 dg */ 
#define W_11_512   0.960430519415566 /* angle 16.17 dg */ 
#define W_12_512   0.953306040354194 /* angle 17.58 dg */ 
#define W_13_512   0.945607325380521 /* angle 18.98 dg */ 
#define W_14_512   0.937339011912575 /* angle 20.39 dg */ 
#define W_15_512   0.928506080473215 /* angle 21.80 dg */ 
#define W_16_512   0.919113851690058 /* angle 23.20 dg */ 
#define W_17_512   0.909167983090522 /* angle 24.61 dg */ 
#define W_18_512   0.898674465693954 /* angle 26.02 dg */ 
#define W_19_512   0.887639620402854 /* angle 27.42 dg */ 
#define W_20_512   0.876070094195407 /* angle 28.83 dg */ 
#define W_21_512   0.863972856121586 /* angle 30.23 dg */ 
#define W_22_512   0.851355193105265 /* angle 31.64 dg */ 
#define W_23_512   0.838224705554838 /* angle 33.05 dg */ 
#define W_24_512   0.824589302785025 /* angle 34.45 dg */ 
#define W_25_512   0.810457198252595 /* angle 35.86 dg */ 
#define W_26_512   0.795836904608883 /* angle 37.27 dg */ 
#define W_27_512   0.780737228572094 /* angle 38.67 dg */ 
#define W_28_512   0.765167265622459 /* angle 40.08 dg */ 
#define W_29_512   0.749136394523459 /* angle 41.48 dg */ 
#define W_30_512   0.732654271672413 /* angle 42.89 dg */ 
#define W_31_512   0.715730825283819 /* angle 44.30 dg */ 
#define W_32_512   0.698376249408972 /* angle 45.70 dg */ 
#define W_33_512   0.680600997795453 /* angle 47.11 dg */ 
#define W_34_512   0.662415777590171 /* angle 48.52 dg */ 
#define W_35_512   0.643831542889791 /* angle 49.92 dg */ 
#define W_36_512   0.624859488142386 /* angle 51.33 dg */ 
#define W_37_512   0.605511041404325 /* angle 52.73 dg */ 
#define W_38_512   0.585797857456439 /* angle 54.14 dg */ 
#define W_39_512   0.565731810783613 /* angle 55.55 dg */ 
#define W_40_512   0.545324988422046 /* angle 56.95 dg */ 
#define W_41_512   0.524589682678469 /* angle 58.36 dg */ 
#define W_42_512   0.503538383725718 /* angle 59.77 dg */ 
#define W_43_512   0.482183772079122 /* angle 61.17 dg */ 
#define W_44_512   0.460538710958240 /* angle 62.58 dg */ 
#define W_45_512   0.438616238538527 /* angle 63.98 dg */ 
#define W_46_512   0.416429560097637 /* angle 65.39 dg */ 
#define W_47_512   0.393992040061048 /* angle 66.80 dg */ 
#define W_48_512   0.371317193951837 /* angle 68.20 dg */ 
#define W_49_512   0.348418680249435 /* angle 69.61 dg */ 
#define W_50_512   0.325310292162263 /* angle 71.02 dg */ 
#define W_51_512   0.302005949319228 /* angle 72.42 dg */ 
#define W_52_512   0.278519689385053 /* angle 73.83 dg */ 
#define W_53_512   0.254865659604514 /* angle 75.23 dg */ 
#define W_54_512   0.231058108280671 /* angle 76.64 dg */ 
#define W_55_512   0.207111376192218 /* angle 78.05 dg */ 
#define W_56_512   0.183039887955141 /* angle 79.45 dg */ 
#define W_57_512   0.158858143333861 /* angle 80.86 dg */ 
#define W_58_512   0.134580708507126 /* angle 82.27 dg */ 
#define W_59_512   0.110222207293883 /* angle 83.67 dg */ 
#define W_60_512   0.085797312344440 /* angle 85.08 dg */ 
#define W_61_512   0.061320736302209 /* angle 86.48 dg */ 
#define W_62_512   0.036807222941359 /* angle 87.89 dg */ 
#define W_63_512   0.012271538285720 /* angle 89.30 dg */ 

typedef struct { double r; double i; } w_type;

#define X2Y(a) (a + (1 << (LN_FFT - 1))) 
#ifdef USE_AVX
#define XMAC(c, a, wr, wi) \
	vec1 = _mm_setr_pd(wr, wi); \
	vec2 = *( __m128d*)&X2Y(a)->r;  \
	vec1 = _mm_hadd_pd(_mm_mul_pd(vec1, _mm_mul_pd(vec2, neg)), \
		 _mm_mul_pd(vec1, _mm_shuffle_pd(vec2, vec2, 1))); \
	*( __m128d*)c = _mm_add_pd(*( __m128d*)a, vec1);
#else
#define XMAC(c, a, wr, wi) \
	c->r = a->r + wr * X2Y(a)->r - wi * X2Y(a)->i; \
	c->i = a->i + wr * X2Y(a)->i + wi * X2Y(a)->r;
#endif

static w_type XY[2][(1 << LN_FFT)];
static const w_type* pOut = LN_FFT % 2 ? &XY[1][0] : &XY[0][0];
static const unsigned short int OutOrder[]={
511,255,383,254,447,253,382,252,479,251,381,250,446,249,380,248,495,247,379,246,445,245,378,244,478,243,377,242,444,241,376,240,503,239,375,238,443,237,374,236,477,235,373,234,442,233,372,232,494,231,371,230,441,229,370,228,476,227,369,226,440,225,368,224,507,223,367,222,439,221,366,220,475,219,365,218,438,217,364,216,493,215,363,214,437,213,362,212,474,211,361,210,436,209,360,208,502,207,359,206,435,205,358,204,473,203,357,202,434,201,356,200,492,199,355,198,433,197,354,196,472,195,353,194,432,193,352,192,509,191,351,190,431,189,350,188,471,187,349,186,430,185,348,184,491,183,347,182,429,181,346,180,470,179,345,178,428,177,344,176,501,175,343,174,427,173,342,172,469,171,341,170,426,169,340,168,490,167,339,166,425,165,338,164,468,163,337,162,424,161,336,160,506,159,335,158,423,157,334,156,467,155,333,154,422,153,332,152,489,151,331,150,421,149,330,148,466,147,329,146,420,145,328,144,500,143,327,142,419,141,326,140,465,139,325,138,418,137,324,136,488,135,323,134,417,133,322,132,464,131,321,130,416,129,320,128,510,127,319,126,415,125,318,124,463,123,317,122,414,121,316,120,487,119,315,118,413,117,314,116,462,115,313,114,412,113,312,112,499,111,311,110,411,109,310,108,461,107,309,106,410,105,308,104,486,103,307,102,409,101,306,100,460,99,305,98,408,97,304,96,505,95,303,94,407,93,302,92,459,91,301,90,406,89,300,88,485,87,299,86,405,85,298,84,458,83,297,82,404,81,296,80,498,79,295,78,403,77,294,76,457,75,293,74,402,73,292,72,484,71,291,70,401,69,290,68,456,67,289,66,400,65,288,64,508,63,287,62,399,61,286,60,455,59,285,58,398,57,284,56,483,55,283,54,397,53,282,52,454,51,281,50,396,49,280,48,497,47,279,46,395,45,278,44,453,43,277,42,394,41,276,40,482,39,275,38,393,37,274,36,452,35,273,34,392,33,272,32,504,31,271,30,391,29,270,28,451,27,269,26,390,25,268,24,481,23,267,22,389,21,266,20,450,19,265,18,388,17,264,16,496,15,263,14,387,13,262,12,449,11,261,10,386,9,260,8,480,7,259,6,385,5,258,4,448,3,257,2,384,1,256,0,};


void fft_caterpillar(double data[], int nn)
{
	int i, j, lim;
	register  w_type *pc, *pa; /* pb = a + (1 << (LN_FFT - 1)) */
#ifdef USE_AVX
	__m128d vec1, vec2, neg = _mm_setr_pd(1.0, -1.0);
#endif
	for (i = 0; i < (1 << LN_FFT); i++) {
		XY[0][i].r = data[2*i+1];
		XY[0][i].i = 0;
	}
	for (i = 1; i <= LN_FFT; i++) {
		pc = i % 2 ? &XY[1][0] : &XY[0][0];
		pa = i % 2 ? &XY[0][0] : &XY[1][0];
		lim = 1 << (LN_FFT - i);
		for (j = 0; j < lim; j++) {
			switch (i) {
			case 9:
				XMAC(pc, pa,  W_0_512, -W_63_512); pc++; pa += 1;
				XMAC(pc, pa,  W_1_512, -W_62_512); pc++; pa += 1;
				XMAC(pc, pa,  W_2_512, -W_61_512); pc++; pa += 1;
				XMAC(pc, pa,  W_3_512, -W_60_512); pc++; pa += 1;
				XMAC(pc, pa,  W_4_512, -W_59_512); pc++; pa += 1;
				XMAC(pc, pa,  W_5_512, -W_58_512); pc++; pa += 1;
				XMAC(pc, pa,  W_6_512, -W_57_512); pc++; pa += 1;
				XMAC(pc, pa,  W_7_512, -W_56_512); pc++; pa += 1;
				XMAC(pc, pa,  W_8_512, -W_55_512); pc++; pa += 1;
				XMAC(pc, pa,  W_9_512, -W_54_512); pc++; pa += 1;
				XMAC(pc, pa,  W_10_512, -W_53_512); pc++; pa += 1;
				XMAC(pc, pa,  W_11_512, -W_52_512); pc++; pa += 1;
				XMAC(pc, pa,  W_12_512, -W_51_512); pc++; pa += 1;
				XMAC(pc, pa,  W_13_512, -W_50_512); pc++; pa += 1;
				XMAC(pc, pa,  W_14_512, -W_49_512); pc++; pa += 1;
				XMAC(pc, pa,  W_15_512, -W_48_512); pc++; pa += 1;
				XMAC(pc, pa,  W_16_512, -W_47_512); pc++; pa += 1;
				XMAC(pc, pa,  W_17_512, -W_46_512); pc++; pa += 1;
				XMAC(pc, pa,  W_18_512, -W_45_512); pc++; pa += 1;
				XMAC(pc, pa,  W_19_512, -W_44_512); pc++; pa += 1;
				XMAC(pc, pa,  W_20_512, -W_43_512); pc++; pa += 1;
				XMAC(pc, pa,  W_21_512, -W_42_512); pc++; pa += 1;
				XMAC(pc, pa,  W_22_512, -W_41_512); pc++; pa += 1;
				XMAC(pc, pa,  W_23_512, -W_40_512); pc++; pa += 1;
				XMAC(pc, pa,  W_24_512, -W_39_512); pc++; pa += 1;
				XMAC(pc, pa,  W_25_512, -W_38_512); pc++; pa += 1;
				XMAC(pc, pa,  W_26_512, -W_37_512); pc++; pa += 1;
				XMAC(pc, pa,  W_27_512, -W_36_512); pc++; pa += 1;
				XMAC(pc, pa,  W_28_512, -W_35_512); pc++; pa += 1;
				XMAC(pc, pa,  W_29_512, -W_34_512); pc++; pa += 1;
				XMAC(pc, pa,  W_30_512, -W_33_512); pc++; pa += 1;
				XMAC(pc, pa,  W_31_512, -W_32_512); pc++; pa += 1;
				XMAC(pc, pa,  W_32_512, -W_31_512); pc++; pa += 1;
				XMAC(pc, pa,  W_33_512, -W_30_512); pc++; pa += 1;
				XMAC(pc, pa,  W_34_512, -W_29_512); pc++; pa += 1;
				XMAC(pc, pa,  W_35_512, -W_28_512); pc++; pa += 1;
				XMAC(pc, pa,  W_36_512, -W_27_512); pc++; pa += 1;
				XMAC(pc, pa,  W_37_512, -W_26_512); pc++; pa += 1;
				XMAC(pc, pa,  W_38_512, -W_25_512); pc++; pa += 1;
				XMAC(pc, pa,  W_39_512, -W_24_512); pc++; pa += 1;
				XMAC(pc, pa,  W_40_512, -W_23_512); pc++; pa += 1;
				XMAC(pc, pa,  W_41_512, -W_22_512); pc++; pa += 1;
				XMAC(pc, pa,  W_42_512, -W_21_512); pc++; pa += 1;
				XMAC(pc, pa,  W_43_512, -W_20_512); pc++; pa += 1;
				XMAC(pc, pa,  W_44_512, -W_19_512); pc++; pa += 1;
				XMAC(pc, pa,  W_45_512, -W_18_512); pc++; pa += 1;
				XMAC(pc, pa,  W_46_512, -W_17_512); pc++; pa += 1;
				XMAC(pc, pa,  W_47_512, -W_16_512); pc++; pa += 1;
				XMAC(pc, pa,  W_48_512, -W_15_512); pc++; pa += 1;
				XMAC(pc, pa,  W_49_512, -W_14_512); pc++; pa += 1;
				XMAC(pc, pa,  W_50_512, -W_13_512); pc++; pa += 1;
				XMAC(pc, pa,  W_51_512, -W_12_512); pc++; pa += 1;
				XMAC(pc, pa,  W_52_512, -W_11_512); pc++; pa += 1;
				XMAC(pc, pa,  W_53_512, -W_10_512); pc++; pa += 1;
				XMAC(pc, pa,  W_54_512, -W_9_512); pc++; pa += 1;
				XMAC(pc, pa,  W_55_512, -W_8_512); pc++; pa += 1;
				XMAC(pc, pa,  W_56_512, -W_7_512); pc++; pa += 1;
				XMAC(pc, pa,  W_57_512, -W_6_512); pc++; pa += 1;
				XMAC(pc, pa,  W_58_512, -W_5_512); pc++; pa += 1;
				XMAC(pc, pa,  W_59_512, -W_4_512); pc++; pa += 1;
				XMAC(pc, pa,  W_60_512, -W_3_512); pc++; pa += 1;
				XMAC(pc, pa,  W_61_512, -W_2_512); pc++; pa += 1;
				XMAC(pc, pa,  W_62_512, -W_1_512); pc++; pa += 1;
				XMAC(pc, pa,  W_63_512, -W_0_512); pc++; pa += 1;
				XMAC(pc, pa, -W_63_512, -W_0_512); pc++; pa += 1;
				XMAC(pc, pa, -W_62_512, -W_1_512); pc++; pa += 1;
				XMAC(pc, pa, -W_61_512, -W_2_512); pc++; pa += 1;
				XMAC(pc, pa, -W_60_512, -W_3_512); pc++; pa += 1;
				XMAC(pc, pa, -W_59_512, -W_4_512); pc++; pa += 1;
				XMAC(pc, pa, -W_58_512, -W_5_512); pc++; pa += 1;
				XMAC(pc, pa, -W_57_512, -W_6_512); pc++; pa += 1;
				XMAC(pc, pa, -W_56_512, -W_7_512); pc++; pa += 1;
				XMAC(pc, pa, -W_55_512, -W_8_512); pc++; pa += 1;
				XMAC(pc, pa, -W_54_512, -W_9_512); pc++; pa += 1;
				XMAC(pc, pa, -W_53_512, -W_10_512); pc++; pa += 1;
				XMAC(pc, pa, -W_52_512, -W_11_512); pc++; pa += 1;
				XMAC(pc, pa, -W_51_512, -W_12_512); pc++; pa += 1;
				XMAC(pc, pa, -W_50_512, -W_13_512); pc++; pa += 1;
				XMAC(pc, pa, -W_49_512, -W_14_512); pc++; pa += 1;
				XMAC(pc, pa, -W_48_512, -W_15_512); pc++; pa += 1;
				XMAC(pc, pa, -W_47_512, -W_16_512); pc++; pa += 1;
				XMAC(pc, pa, -W_46_512, -W_17_512); pc++; pa += 1;
				XMAC(pc, pa, -W_45_512, -W_18_512); pc++; pa += 1;
				XMAC(pc, pa, -W_44_512, -W_19_512); pc++; pa += 1;
				XMAC(pc, pa, -W_43_512, -W_20_512); pc++; pa += 1;
				XMAC(pc, pa, -W_42_512, -W_21_512); pc++; pa += 1;
				XMAC(pc, pa, -W_41_512, -W_22_512); pc++; pa += 1;
				XMAC(pc, pa, -W_40_512, -W_23_512); pc++; pa += 1;
				XMAC(pc, pa, -W_39_512, -W_24_512); pc++; pa += 1;
				XMAC(pc, pa, -W_38_512, -W_25_512); pc++; pa += 1;
				XMAC(pc, pa, -W_37_512, -W_26_512); pc++; pa += 1;
				XMAC(pc, pa, -W_36_512, -W_27_512); pc++; pa += 1;
				XMAC(pc, pa, -W_35_512, -W_28_512); pc++; pa += 1;
				XMAC(pc, pa, -W_34_512, -W_29_512); pc++; pa += 1;
				XMAC(pc, pa, -W_33_512, -W_30_512); pc++; pa += 1;
				XMAC(pc, pa, -W_32_512, -W_31_512); pc++; pa += 1;
				XMAC(pc, pa, -W_31_512, -W_32_512); pc++; pa += 1;
				XMAC(pc, pa, -W_30_512, -W_33_512); pc++; pa += 1;
				XMAC(pc, pa, -W_29_512, -W_34_512); pc++; pa += 1;
				XMAC(pc, pa, -W_28_512, -W_35_512); pc++; pa += 1;
				XMAC(pc, pa, -W_27_512, -W_36_512); pc++; pa += 1;
				XMAC(pc, pa, -W_26_512, -W_37_512); pc++; pa += 1;
				XMAC(pc, pa, -W_25_512, -W_38_512); pc++; pa += 1;
				XMAC(pc, pa, -W_24_512, -W_39_512); pc++; pa += 1;
				XMAC(pc, pa, -W_23_512, -W_40_512); pc++; pa += 1;
				XMAC(pc, pa, -W_22_512, -W_41_512); pc++; pa += 1;
				XMAC(pc, pa, -W_21_512, -W_42_512); pc++; pa += 1;
				XMAC(pc, pa, -W_20_512, -W_43_512); pc++; pa += 1;
				XMAC(pc, pa, -W_19_512, -W_44_512); pc++; pa += 1;
				XMAC(pc, pa, -W_18_512, -W_45_512); pc++; pa += 1;
				XMAC(pc, pa, -W_17_512, -W_46_512); pc++; pa += 1;
				XMAC(pc, pa, -W_16_512, -W_47_512); pc++; pa += 1;
				XMAC(pc, pa, -W_15_512, -W_48_512); pc++; pa += 1;
				XMAC(pc, pa, -W_14_512, -W_49_512); pc++; pa += 1;
				XMAC(pc, pa, -W_13_512, -W_50_512); pc++; pa += 1;
				XMAC(pc, pa, -W_12_512, -W_51_512); pc++; pa += 1;
				XMAC(pc, pa, -W_11_512, -W_52_512); pc++; pa += 1;
				XMAC(pc, pa, -W_10_512, -W_53_512); pc++; pa += 1;
				XMAC(pc, pa, -W_9_512, -W_54_512); pc++; pa += 1;
				XMAC(pc, pa, -W_8_512, -W_55_512); pc++; pa += 1;
				XMAC(pc, pa, -W_7_512, -W_56_512); pc++; pa += 1;
				XMAC(pc, pa, -W_6_512, -W_57_512); pc++; pa += 1;
				XMAC(pc, pa, -W_5_512, -W_58_512); pc++; pa += 1;
				XMAC(pc, pa, -W_4_512, -W_59_512); pc++; pa += 1;
				XMAC(pc, pa, -W_3_512, -W_60_512); pc++; pa += 1;
				XMAC(pc, pa, -W_2_512, -W_61_512); pc++; pa += 1;
				XMAC(pc, pa, -W_1_512, -W_62_512); pc++; pa += 1;
				XMAC(pc, pa, -W_0_512, -W_63_512); pc++; pa += 1;
				pa -= 128;
				XMAC(pc, pa, -W_0_512, +W_63_512); pc++; pa += 1;
				XMAC(pc, pa, -W_1_512, +W_62_512); pc++; pa += 1;
				XMAC(pc, pa, -W_2_512, +W_61_512); pc++; pa += 1;
				XMAC(pc, pa, -W_3_512, +W_60_512); pc++; pa += 1;
				XMAC(pc, pa, -W_4_512, +W_59_512); pc++; pa += 1;
				XMAC(pc, pa, -W_5_512, +W_58_512); pc++; pa += 1;
				XMAC(pc, pa, -W_6_512, +W_57_512); pc++; pa += 1;
				XMAC(pc, pa, -W_7_512, +W_56_512); pc++; pa += 1;
				XMAC(pc, pa, -W_8_512, +W_55_512); pc++; pa += 1;
				XMAC(pc, pa, -W_9_512, +W_54_512); pc++; pa += 1;
				XMAC(pc, pa, -W_10_512, +W_53_512); pc++; pa += 1;
				XMAC(pc, pa, -W_11_512, +W_52_512); pc++; pa += 1;
				XMAC(pc, pa, -W_12_512, +W_51_512); pc++; pa += 1;
				XMAC(pc, pa, -W_13_512, +W_50_512); pc++; pa += 1;
				XMAC(pc, pa, -W_14_512, +W_49_512); pc++; pa += 1;
				XMAC(pc, pa, -W_15_512, +W_48_512); pc++; pa += 1;
				XMAC(pc, pa, -W_16_512, +W_47_512); pc++; pa += 1;
				XMAC(pc, pa, -W_17_512, +W_46_512); pc++; pa += 1;
				XMAC(pc, pa, -W_18_512, +W_45_512); pc++; pa += 1;
				XMAC(pc, pa, -W_19_512, +W_44_512); pc++; pa += 1;
				XMAC(pc, pa, -W_20_512, +W_43_512); pc++; pa += 1;
				XMAC(pc, pa, -W_21_512, +W_42_512); pc++; pa += 1;
				XMAC(pc, pa, -W_22_512, +W_41_512); pc++; pa += 1;
				XMAC(pc, pa, -W_23_512, +W_40_512); pc++; pa += 1;
				XMAC(pc, pa, -W_24_512, +W_39_512); pc++; pa += 1;
				XMAC(pc, pa, -W_25_512, +W_38_512); pc++; pa += 1;
				XMAC(pc, pa, -W_26_512, +W_37_512); pc++; pa += 1;
				XMAC(pc, pa, -W_27_512, +W_36_512); pc++; pa += 1;
				XMAC(pc, pa, -W_28_512, +W_35_512); pc++; pa += 1;
				XMAC(pc, pa, -W_29_512, +W_34_512); pc++; pa += 1;
				XMAC(pc, pa, -W_30_512, +W_33_512); pc++; pa += 1;
				XMAC(pc, pa, -W_31_512, +W_32_512); pc++; pa += 1;
				XMAC(pc, pa, -W_32_512, +W_31_512); pc++; pa += 1;
				XMAC(pc, pa, -W_33_512, +W_30_512); pc++; pa += 1;
				XMAC(pc, pa, -W_34_512, +W_29_512); pc++; pa += 1;
				XMAC(pc, pa, -W_35_512, +W_28_512); pc++; pa += 1;
				XMAC(pc, pa, -W_36_512, +W_27_512); pc++; pa += 1;
				XMAC(pc, pa, -W_37_512, +W_26_512); pc++; pa += 1;
				XMAC(pc, pa, -W_38_512, +W_25_512); pc++; pa += 1;
				XMAC(pc, pa, -W_39_512, +W_24_512); pc++; pa += 1;
				XMAC(pc, pa, -W_40_512, +W_23_512); pc++; pa += 1;
				XMAC(pc, pa, -W_41_512, +W_22_512); pc++; pa += 1;
				XMAC(pc, pa, -W_42_512, +W_21_512); pc++; pa += 1;
				XMAC(pc, pa, -W_43_512, +W_20_512); pc++; pa += 1;
				XMAC(pc, pa, -W_44_512, +W_19_512); pc++; pa += 1;
				XMAC(pc, pa, -W_45_512, +W_18_512); pc++; pa += 1;
				XMAC(pc, pa, -W_46_512, +W_17_512); pc++; pa += 1;
				XMAC(pc, pa, -W_47_512, +W_16_512); pc++; pa += 1;
				XMAC(pc, pa, -W_48_512, +W_15_512); pc++; pa += 1;
				XMAC(pc, pa, -W_49_512, +W_14_512); pc++; pa += 1;
				XMAC(pc, pa, -W_50_512, +W_13_512); pc++; pa += 1;
				XMAC(pc, pa, -W_51_512, +W_12_512); pc++; pa += 1;
				XMAC(pc, pa, -W_52_512, +W_11_512); pc++; pa += 1;
				XMAC(pc, pa, -W_53_512, +W_10_512); pc++; pa += 1;
				XMAC(pc, pa, -W_54_512, +W_9_512); pc++; pa += 1;
				XMAC(pc, pa, -W_55_512, +W_8_512); pc++; pa += 1;
				XMAC(pc, pa, -W_56_512, +W_7_512); pc++; pa += 1;
				XMAC(pc, pa, -W_57_512, +W_6_512); pc++; pa += 1;
				XMAC(pc, pa, -W_58_512, +W_5_512); pc++; pa += 1;
				XMAC(pc, pa, -W_59_512, +W_4_512); pc++; pa += 1;
				XMAC(pc, pa, -W_60_512, +W_3_512); pc++; pa += 1;
				XMAC(pc, pa, -W_61_512, +W_2_512); pc++; pa += 1;
				XMAC(pc, pa, -W_62_512, +W_1_512); pc++; pa += 1;
				XMAC(pc, pa, -W_63_512, +W_0_512); pc++; pa += 1;
				XMAC(pc, pa,  W_63_512, +W_0_512); pc++; pa += 1;
				XMAC(pc, pa,  W_62_512, +W_1_512); pc++; pa += 1;
				XMAC(pc, pa,  W_61_512, +W_2_512); pc++; pa += 1;
				XMAC(pc, pa,  W_60_512, +W_3_512); pc++; pa += 1;
				XMAC(pc, pa,  W_59_512, +W_4_512); pc++; pa += 1;
				XMAC(pc, pa,  W_58_512, +W_5_512); pc++; pa += 1;
				XMAC(pc, pa,  W_57_512, +W_6_512); pc++; pa += 1;
				XMAC(pc, pa,  W_56_512, +W_7_512); pc++; pa += 1;
				XMAC(pc, pa,  W_55_512, +W_8_512); pc++; pa += 1;
				XMAC(pc, pa,  W_54_512, +W_9_512); pc++; pa += 1;
				XMAC(pc, pa,  W_53_512, +W_10_512); pc++; pa += 1;
				XMAC(pc, pa,  W_52_512, +W_11_512); pc++; pa += 1;
				XMAC(pc, pa,  W_51_512, +W_12_512); pc++; pa += 1;
				XMAC(pc, pa,  W_50_512, +W_13_512); pc++; pa += 1;
				XMAC(pc, pa,  W_49_512, +W_14_512); pc++; pa += 1;
				XMAC(pc, pa,  W_48_512, +W_15_512); pc++; pa += 1;
				XMAC(pc, pa,  W_47_512, +W_16_512); pc++; pa += 1;
				XMAC(pc, pa,  W_46_512, +W_17_512); pc++; pa += 1;
				XMAC(pc, pa,  W_45_512, +W_18_512); pc++; pa += 1;
				XMAC(pc, pa,  W_44_512, +W_19_512); pc++; pa += 1;
				XMAC(pc, pa,  W_43_512, +W_20_512); pc++; pa += 1;
				XMAC(pc, pa,  W_42_512, +W_21_512); pc++; pa += 1;
				XMAC(pc, pa,  W_41_512, +W_22_512); pc++; pa += 1;
				XMAC(pc, pa,  W_40_512, +W_23_512); pc++; pa += 1;
				XMAC(pc, pa,  W_39_512, +W_24_512); pc++; pa += 1;
				XMAC(pc, pa,  W_38_512, +W_25_512); pc++; pa += 1;
				XMAC(pc, pa,  W_37_512, +W_26_512); pc++; pa += 1;
				XMAC(pc, pa,  W_36_512, +W_27_512); pc++; pa += 1;
				XMAC(pc, pa,  W_35_512, +W_28_512); pc++; pa += 1;
				XMAC(pc, pa,  W_34_512, +W_29_512); pc++; pa += 1;
				XMAC(pc, pa,  W_33_512, +W_30_512); pc++; pa += 1;
				XMAC(pc, pa,  W_32_512, +W_31_512); pc++; pa += 1;
				XMAC(pc, pa,  W_31_512, +W_32_512); pc++; pa += 1;
				XMAC(pc, pa,  W_30_512, +W_33_512); pc++; pa += 1;
				XMAC(pc, pa,  W_29_512, +W_34_512); pc++; pa += 1;
				XMAC(pc, pa,  W_28_512, +W_35_512); pc++; pa += 1;
				XMAC(pc, pa,  W_27_512, +W_36_512); pc++; pa += 1;
				XMAC(pc, pa,  W_26_512, +W_37_512); pc++; pa += 1;
				XMAC(pc, pa,  W_25_512, +W_38_512); pc++; pa += 1;
				XMAC(pc, pa,  W_24_512, +W_39_512); pc++; pa += 1;
				XMAC(pc, pa,  W_23_512, +W_40_512); pc++; pa += 1;
				XMAC(pc, pa,  W_22_512, +W_41_512); pc++; pa += 1;
				XMAC(pc, pa,  W_21_512, +W_42_512); pc++; pa += 1;
				XMAC(pc, pa,  W_20_512, +W_43_512); pc++; pa += 1;
				XMAC(pc, pa,  W_19_512, +W_44_512); pc++; pa += 1;
				XMAC(pc, pa,  W_18_512, +W_45_512); pc++; pa += 1;
				XMAC(pc, pa,  W_17_512, +W_46_512); pc++; pa += 1;
				XMAC(pc, pa,  W_16_512, +W_47_512); pc++; pa += 1;
				XMAC(pc, pa,  W_15_512, +W_48_512); pc++; pa += 1;
				XMAC(pc, pa,  W_14_512, +W_49_512); pc++; pa += 1;
				XMAC(pc, pa,  W_13_512, +W_50_512); pc++; pa += 1;
				XMAC(pc, pa,  W_12_512, +W_51_512); pc++; pa += 1;
				XMAC(pc, pa,  W_11_512, +W_52_512); pc++; pa += 1;
				XMAC(pc, pa,  W_10_512, +W_53_512); pc++; pa += 1;
				XMAC(pc, pa,  W_9_512, +W_54_512); pc++; pa += 1;
				XMAC(pc, pa,  W_8_512, +W_55_512); pc++; pa += 1;
				XMAC(pc, pa,  W_7_512, +W_56_512); pc++; pa += 1;
				XMAC(pc, pa,  W_6_512, +W_57_512); pc++; pa += 1;
				XMAC(pc, pa,  W_5_512, +W_58_512); pc++; pa += 1;
				XMAC(pc, pa,  W_4_512, +W_59_512); pc++; pa += 1;
				XMAC(pc, pa,  W_3_512, +W_60_512); pc++; pa += 1;
				XMAC(pc, pa,  W_2_512, +W_61_512); pc++; pa += 1;
				XMAC(pc, pa,  W_1_512, +W_62_512); pc++; pa += 1;
				XMAC(pc, pa,  W_0_512, +W_63_512); pc++; pa += 1;
			case 8:
				XMAC(pc, pa,  W_0_256, -W_31_256); pc++; pa += 1;
				XMAC(pc, pa,  W_1_256, -W_30_256); pc++; pa += 1;
				XMAC(pc, pa,  W_2_256, -W_29_256); pc++; pa += 1;
				XMAC(pc, pa,  W_3_256, -W_28_256); pc++; pa += 1;
				XMAC(pc, pa,  W_4_256, -W_27_256); pc++; pa += 1;
				XMAC(pc, pa,  W_5_256, -W_26_256); pc++; pa += 1;
				XMAC(pc, pa,  W_6_256, -W_25_256); pc++; pa += 1;
				XMAC(pc, pa,  W_7_256, -W_24_256); pc++; pa += 1;
				XMAC(pc, pa,  W_8_256, -W_23_256); pc++; pa += 1;
				XMAC(pc, pa,  W_9_256, -W_22_256); pc++; pa += 1;
				XMAC(pc, pa,  W_10_256, -W_21_256); pc++; pa += 1;
				XMAC(pc, pa,  W_11_256, -W_20_256); pc++; pa += 1;
				XMAC(pc, pa,  W_12_256, -W_19_256); pc++; pa += 1;
				XMAC(pc, pa,  W_13_256, -W_18_256); pc++; pa += 1;
				XMAC(pc, pa,  W_14_256, -W_17_256); pc++; pa += 1;
				XMAC(pc, pa,  W_15_256, -W_16_256); pc++; pa += 1;
				XMAC(pc, pa,  W_16_256, -W_15_256); pc++; pa += 1;
				XMAC(pc, pa,  W_17_256, -W_14_256); pc++; pa += 1;
				XMAC(pc, pa,  W_18_256, -W_13_256); pc++; pa += 1;
				XMAC(pc, pa,  W_19_256, -W_12_256); pc++; pa += 1;
				XMAC(pc, pa,  W_20_256, -W_11_256); pc++; pa += 1;
				XMAC(pc, pa,  W_21_256, -W_10_256); pc++; pa += 1;
				XMAC(pc, pa,  W_22_256, -W_9_256); pc++; pa += 1;
				XMAC(pc, pa,  W_23_256, -W_8_256); pc++; pa += 1;
				XMAC(pc, pa,  W_24_256, -W_7_256); pc++; pa += 1;
				XMAC(pc, pa,  W_25_256, -W_6_256); pc++; pa += 1;
				XMAC(pc, pa,  W_26_256, -W_5_256); pc++; pa += 1;
				XMAC(pc, pa,  W_27_256, -W_4_256); pc++; pa += 1;
				XMAC(pc, pa,  W_28_256, -W_3_256); pc++; pa += 1;
				XMAC(pc, pa,  W_29_256, -W_2_256); pc++; pa += 1;
				XMAC(pc, pa,  W_30_256, -W_1_256); pc++; pa += 1;
				XMAC(pc, pa,  W_31_256, -W_0_256); pc++; pa += 1;
				XMAC(pc, pa, -W_31_256, -W_0_256); pc++; pa += 1;
				XMAC(pc, pa, -W_30_256, -W_1_256); pc++; pa += 1;
				XMAC(pc, pa, -W_29_256, -W_2_256); pc++; pa += 1;
				XMAC(pc, pa, -W_28_256, -W_3_256); pc++; pa += 1;
				XMAC(pc, pa, -W_27_256, -W_4_256); pc++; pa += 1;
				XMAC(pc, pa, -W_26_256, -W_5_256); pc++; pa += 1;
				XMAC(pc, pa, -W_25_256, -W_6_256); pc++; pa += 1;
				XMAC(pc, pa, -W_24_256, -W_7_256); pc++; pa += 1;
				XMAC(pc, pa, -W_23_256, -W_8_256); pc++; pa += 1;
				XMAC(pc, pa, -W_22_256, -W_9_256); pc++; pa += 1;
				XMAC(pc, pa, -W_21_256, -W_10_256); pc++; pa += 1;
				XMAC(pc, pa, -W_20_256, -W_11_256); pc++; pa += 1;
				XMAC(pc, pa, -W_19_256, -W_12_256); pc++; pa += 1;
				XMAC(pc, pa, -W_18_256, -W_13_256); pc++; pa += 1;
				XMAC(pc, pa, -W_17_256, -W_14_256); pc++; pa += 1;
				XMAC(pc, pa, -W_16_256, -W_15_256); pc++; pa += 1;
				XMAC(pc, pa, -W_15_256, -W_16_256); pc++; pa += 1;
				XMAC(pc, pa, -W_14_256, -W_17_256); pc++; pa += 1;
				XMAC(pc, pa, -W_13_256, -W_18_256); pc++; pa += 1;
				XMAC(pc, pa, -W_12_256, -W_19_256); pc++; pa += 1;
				XMAC(pc, pa, -W_11_256, -W_20_256); pc++; pa += 1;
				XMAC(pc, pa, -W_10_256, -W_21_256); pc++; pa += 1;
				XMAC(pc, pa, -W_9_256, -W_22_256); pc++; pa += 1;
				XMAC(pc, pa, -W_8_256, -W_23_256); pc++; pa += 1;
				XMAC(pc, pa, -W_7_256, -W_24_256); pc++; pa += 1;
				XMAC(pc, pa, -W_6_256, -W_25_256); pc++; pa += 1;
				XMAC(pc, pa, -W_5_256, -W_26_256); pc++; pa += 1;
				XMAC(pc, pa, -W_4_256, -W_27_256); pc++; pa += 1;
				XMAC(pc, pa, -W_3_256, -W_28_256); pc++; pa += 1;
				XMAC(pc, pa, -W_2_256, -W_29_256); pc++; pa += 1;
				XMAC(pc, pa, -W_1_256, -W_30_256); pc++; pa += 1;
				XMAC(pc, pa, -W_0_256, -W_31_256); pc++; pa += 1;
				pa -= 64;
				XMAC(pc, pa, -W_0_256, +W_31_256); pc++; pa += 1;
				XMAC(pc, pa, -W_1_256, +W_30_256); pc++; pa += 1;
				XMAC(pc, pa, -W_2_256, +W_29_256); pc++; pa += 1;
				XMAC(pc, pa, -W_3_256, +W_28_256); pc++; pa += 1;
				XMAC(pc, pa, -W_4_256, +W_27_256); pc++; pa += 1;
				XMAC(pc, pa, -W_5_256, +W_26_256); pc++; pa += 1;
				XMAC(pc, pa, -W_6_256, +W_25_256); pc++; pa += 1;
				XMAC(pc, pa, -W_7_256, +W_24_256); pc++; pa += 1;
				XMAC(pc, pa, -W_8_256, +W_23_256); pc++; pa += 1;
				XMAC(pc, pa, -W_9_256, +W_22_256); pc++; pa += 1;
				XMAC(pc, pa, -W_10_256, +W_21_256); pc++; pa += 1;
				XMAC(pc, pa, -W_11_256, +W_20_256); pc++; pa += 1;
				XMAC(pc, pa, -W_12_256, +W_19_256); pc++; pa += 1;
				XMAC(pc, pa, -W_13_256, +W_18_256); pc++; pa += 1;
				XMAC(pc, pa, -W_14_256, +W_17_256); pc++; pa += 1;
				XMAC(pc, pa, -W_15_256, +W_16_256); pc++; pa += 1;
				XMAC(pc, pa, -W_16_256, +W_15_256); pc++; pa += 1;
				XMAC(pc, pa, -W_17_256, +W_14_256); pc++; pa += 1;
				XMAC(pc, pa, -W_18_256, +W_13_256); pc++; pa += 1;
				XMAC(pc, pa, -W_19_256, +W_12_256); pc++; pa += 1;
				XMAC(pc, pa, -W_20_256, +W_11_256); pc++; pa += 1;
				XMAC(pc, pa, -W_21_256, +W_10_256); pc++; pa += 1;
				XMAC(pc, pa, -W_22_256, +W_9_256); pc++; pa += 1;
				XMAC(pc, pa, -W_23_256, +W_8_256); pc++; pa += 1;
				XMAC(pc, pa, -W_24_256, +W_7_256); pc++; pa += 1;
				XMAC(pc, pa, -W_25_256, +W_6_256); pc++; pa += 1;
				XMAC(pc, pa, -W_26_256, +W_5_256); pc++; pa += 1;
				XMAC(pc, pa, -W_27_256, +W_4_256); pc++; pa += 1;
				XMAC(pc, pa, -W_28_256, +W_3_256); pc++; pa += 1;
				XMAC(pc, pa, -W_29_256, +W_2_256); pc++; pa += 1;
				XMAC(pc, pa, -W_30_256, +W_1_256); pc++; pa += 1;
				XMAC(pc, pa, -W_31_256, +W_0_256); pc++; pa += 1;
				XMAC(pc, pa,  W_31_256, +W_0_256); pc++; pa += 1;
				XMAC(pc, pa,  W_30_256, +W_1_256); pc++; pa += 1;
				XMAC(pc, pa,  W_29_256, +W_2_256); pc++; pa += 1;
				XMAC(pc, pa,  W_28_256, +W_3_256); pc++; pa += 1;
				XMAC(pc, pa,  W_27_256, +W_4_256); pc++; pa += 1;
				XMAC(pc, pa,  W_26_256, +W_5_256); pc++; pa += 1;
				XMAC(pc, pa,  W_25_256, +W_6_256); pc++; pa += 1;
				XMAC(pc, pa,  W_24_256, +W_7_256); pc++; pa += 1;
				XMAC(pc, pa,  W_23_256, +W_8_256); pc++; pa += 1;
				XMAC(pc, pa,  W_22_256, +W_9_256); pc++; pa += 1;
				XMAC(pc, pa,  W_21_256, +W_10_256); pc++; pa += 1;
				XMAC(pc, pa,  W_20_256, +W_11_256); pc++; pa += 1;
				XMAC(pc, pa,  W_19_256, +W_12_256); pc++; pa += 1;
				XMAC(pc, pa,  W_18_256, +W_13_256); pc++; pa += 1;
				XMAC(pc, pa,  W_17_256, +W_14_256); pc++; pa += 1;
				XMAC(pc, pa,  W_16_256, +W_15_256); pc++; pa += 1;
				XMAC(pc, pa,  W_15_256, +W_16_256); pc++; pa += 1;
				XMAC(pc, pa,  W_14_256, +W_17_256); pc++; pa += 1;
				XMAC(pc, pa,  W_13_256, +W_18_256); pc++; pa += 1;
				XMAC(pc, pa,  W_12_256, +W_19_256); pc++; pa += 1;
				XMAC(pc, pa,  W_11_256, +W_20_256); pc++; pa += 1;
				XMAC(pc, pa,  W_10_256, +W_21_256); pc++; pa += 1;
				XMAC(pc, pa,  W_9_256, +W_22_256); pc++; pa += 1;
				XMAC(pc, pa,  W_8_256, +W_23_256); pc++; pa += 1;
				XMAC(pc, pa,  W_7_256, +W_24_256); pc++; pa += 1;
				XMAC(pc, pa,  W_6_256, +W_25_256); pc++; pa += 1;
				XMAC(pc, pa,  W_5_256, +W_26_256); pc++; pa += 1;
				XMAC(pc, pa,  W_4_256, +W_27_256); pc++; pa += 1;
				XMAC(pc, pa,  W_3_256, +W_28_256); pc++; pa += 1;
				XMAC(pc, pa,  W_2_256, +W_29_256); pc++; pa += 1;
				XMAC(pc, pa,  W_1_256, +W_30_256); pc++; pa += 1;
				XMAC(pc, pa,  W_0_256, +W_31_256); pc++; pa += 1;
			case 7:
				XMAC(pc, pa,  W_0_128, -W_15_128); pc++; pa += 1;
				XMAC(pc, pa,  W_1_128, -W_14_128); pc++; pa += 1;
				XMAC(pc, pa,  W_2_128, -W_13_128); pc++; pa += 1;
				XMAC(pc, pa,  W_3_128, -W_12_128); pc++; pa += 1;
				XMAC(pc, pa,  W_4_128, -W_11_128); pc++; pa += 1;
				XMAC(pc, pa,  W_5_128, -W_10_128); pc++; pa += 1;
				XMAC(pc, pa,  W_6_128, -W_9_128); pc++; pa += 1;
				XMAC(pc, pa,  W_7_128, -W_8_128); pc++; pa += 1;
				XMAC(pc, pa,  W_8_128, -W_7_128); pc++; pa += 1;
				XMAC(pc, pa,  W_9_128, -W_6_128); pc++; pa += 1;
				XMAC(pc, pa,  W_10_128, -W_5_128); pc++; pa += 1;
				XMAC(pc, pa,  W_11_128, -W_4_128); pc++; pa += 1;
				XMAC(pc, pa,  W_12_128, -W_3_128); pc++; pa += 1;
				XMAC(pc, pa,  W_13_128, -W_2_128); pc++; pa += 1;
				XMAC(pc, pa,  W_14_128, -W_1_128); pc++; pa += 1;
				XMAC(pc, pa,  W_15_128, -W_0_128); pc++; pa += 1;
				XMAC(pc, pa, -W_15_128, -W_0_128); pc++; pa += 1;
				XMAC(pc, pa, -W_14_128, -W_1_128); pc++; pa += 1;
				XMAC(pc, pa, -W_13_128, -W_2_128); pc++; pa += 1;
				XMAC(pc, pa, -W_12_128, -W_3_128); pc++; pa += 1;
				XMAC(pc, pa, -W_11_128, -W_4_128); pc++; pa += 1;
				XMAC(pc, pa, -W_10_128, -W_5_128); pc++; pa += 1;
				XMAC(pc, pa, -W_9_128, -W_6_128); pc++; pa += 1;
				XMAC(pc, pa, -W_8_128, -W_7_128); pc++; pa += 1;
				XMAC(pc, pa, -W_7_128, -W_8_128); pc++; pa += 1;
				XMAC(pc, pa, -W_6_128, -W_9_128); pc++; pa += 1;
				XMAC(pc, pa, -W_5_128, -W_10_128); pc++; pa += 1;
				XMAC(pc, pa, -W_4_128, -W_11_128); pc++; pa += 1;
				XMAC(pc, pa, -W_3_128, -W_12_128); pc++; pa += 1;
				XMAC(pc, pa, -W_2_128, -W_13_128); pc++; pa += 1;
				XMAC(pc, pa, -W_1_128, -W_14_128); pc++; pa += 1;
				XMAC(pc, pa, -W_0_128, -W_15_128); pc++; pa += 1;
				pa -= 32;
				XMAC(pc, pa, -W_0_128, +W_15_128); pc++; pa += 1;
				XMAC(pc, pa, -W_1_128, +W_14_128); pc++; pa += 1;
				XMAC(pc, pa, -W_2_128, +W_13_128); pc++; pa += 1;
				XMAC(pc, pa, -W_3_128, +W_12_128); pc++; pa += 1;
				XMAC(pc, pa, -W_4_128, +W_11_128); pc++; pa += 1;
				XMAC(pc, pa, -W_5_128, +W_10_128); pc++; pa += 1;
				XMAC(pc, pa, -W_6_128, +W_9_128); pc++; pa += 1;
				XMAC(pc, pa, -W_7_128, +W_8_128); pc++; pa += 1;
				XMAC(pc, pa, -W_8_128, +W_7_128); pc++; pa += 1;
				XMAC(pc, pa, -W_9_128, +W_6_128); pc++; pa += 1;
				XMAC(pc, pa, -W_10_128, +W_5_128); pc++; pa += 1;
				XMAC(pc, pa, -W_11_128, +W_4_128); pc++; pa += 1;
				XMAC(pc, pa, -W_12_128, +W_3_128); pc++; pa += 1;
				XMAC(pc, pa, -W_13_128, +W_2_128); pc++; pa += 1;
				XMAC(pc, pa, -W_14_128, +W_1_128); pc++; pa += 1;
				XMAC(pc, pa, -W_15_128, +W_0_128); pc++; pa += 1;
				XMAC(pc, pa,  W_15_128, +W_0_128); pc++; pa += 1;
				XMAC(pc, pa,  W_14_128, +W_1_128); pc++; pa += 1;
				XMAC(pc, pa,  W_13_128, +W_2_128); pc++; pa += 1;
				XMAC(pc, pa,  W_12_128, +W_3_128); pc++; pa += 1;
				XMAC(pc, pa,  W_11_128, +W_4_128); pc++; pa += 1;
				XMAC(pc, pa,  W_10_128, +W_5_128); pc++; pa += 1;
				XMAC(pc, pa,  W_9_128, +W_6_128); pc++; pa += 1;
				XMAC(pc, pa,  W_8_128, +W_7_128); pc++; pa += 1;
				XMAC(pc, pa,  W_7_128, +W_8_128); pc++; pa += 1;
				XMAC(pc, pa,  W_6_128, +W_9_128); pc++; pa += 1;
				XMAC(pc, pa,  W_5_128, +W_10_128); pc++; pa += 1;
				XMAC(pc, pa,  W_4_128, +W_11_128); pc++; pa += 1;
				XMAC(pc, pa,  W_3_128, +W_12_128); pc++; pa += 1;
				XMAC(pc, pa,  W_2_128, +W_13_128); pc++; pa += 1;
				XMAC(pc, pa,  W_1_128, +W_14_128); pc++; pa += 1;
				XMAC(pc, pa,  W_0_128, +W_15_128); pc++; pa += 1;
			case 6:
				XMAC(pc, pa,  W_0_64, -W_7_64); pc++; pa += 1;
				XMAC(pc, pa,  W_1_64, -W_6_64); pc++; pa += 1;
				XMAC(pc, pa,  W_2_64, -W_5_64); pc++; pa += 1;
				XMAC(pc, pa,  W_3_64, -W_4_64); pc++; pa += 1;
				XMAC(pc, pa,  W_4_64, -W_3_64); pc++; pa += 1;
				XMAC(pc, pa,  W_5_64, -W_2_64); pc++; pa += 1;
				XMAC(pc, pa,  W_6_64, -W_1_64); pc++; pa += 1;
				XMAC(pc, pa,  W_7_64, -W_0_64); pc++; pa += 1;
				XMAC(pc, pa, -W_7_64, -W_0_64); pc++; pa += 1;
				XMAC(pc, pa, -W_6_64, -W_1_64); pc++; pa += 1;
				XMAC(pc, pa, -W_5_64, -W_2_64); pc++; pa += 1;
				XMAC(pc, pa, -W_4_64, -W_3_64); pc++; pa += 1;
				XMAC(pc, pa, -W_3_64, -W_4_64); pc++; pa += 1;
				XMAC(pc, pa, -W_2_64, -W_5_64); pc++; pa += 1;
				XMAC(pc, pa, -W_1_64, -W_6_64); pc++; pa += 1;
				XMAC(pc, pa, -W_0_64, -W_7_64); pc++; pa += 1;
				pa -= 16;
				XMAC(pc, pa, -W_0_64, +W_7_64); pc++; pa += 1;
				XMAC(pc, pa, -W_1_64, +W_6_64); pc++; pa += 1;
				XMAC(pc, pa, -W_2_64, +W_5_64); pc++; pa += 1;
				XMAC(pc, pa, -W_3_64, +W_4_64); pc++; pa += 1;
				XMAC(pc, pa, -W_4_64, +W_3_64); pc++; pa += 1;
				XMAC(pc, pa, -W_5_64, +W_2_64); pc++; pa += 1;
				XMAC(pc, pa, -W_6_64, +W_1_64); pc++; pa += 1;
				XMAC(pc, pa, -W_7_64, +W_0_64); pc++; pa += 1;
				XMAC(pc, pa,  W_7_64, +W_0_64); pc++; pa += 1;
				XMAC(pc, pa,  W_6_64, +W_1_64); pc++; pa += 1;
				XMAC(pc, pa,  W_5_64, +W_2_64); pc++; pa += 1;
				XMAC(pc, pa,  W_4_64, +W_3_64); pc++; pa += 1;
				XMAC(pc, pa,  W_3_64, +W_4_64); pc++; pa += 1;
				XMAC(pc, pa,  W_2_64, +W_5_64); pc++; pa += 1;
				XMAC(pc, pa,  W_1_64, +W_6_64); pc++; pa += 1;
				XMAC(pc, pa,  W_0_64, +W_7_64); pc++; pa += 1;
			case 5:
				XMAC(pc, pa,  W_0_32, -W_3_32); pc++; pa += 1;
				XMAC(pc, pa,  W_1_32, -W_2_32); pc++; pa += 1;
				XMAC(pc, pa,  W_2_32, -W_1_32); pc++; pa += 1;
				XMAC(pc, pa,  W_3_32, -W_0_32); pc++; pa += 1;
				XMAC(pc, pa, -W_3_32, -W_0_32); pc++; pa += 1;
				XMAC(pc, pa, -W_2_32, -W_1_32); pc++; pa += 1;
				XMAC(pc, pa, -W_1_32, -W_2_32); pc++; pa += 1;
				XMAC(pc, pa, -W_0_32, -W_3_32); pc++; pa += 1;
				pa -= 8;
				XMAC(pc, pa, -W_0_32, +W_3_32); pc++; pa += 1;
				XMAC(pc, pa, -W_1_32, +W_2_32); pc++; pa += 1;
				XMAC(pc, pa, -W_2_32, +W_1_32); pc++; pa += 1;
				XMAC(pc, pa, -W_3_32, +W_0_32); pc++; pa += 1;
				XMAC(pc, pa,  W_3_32, +W_0_32); pc++; pa += 1;
				XMAC(pc, pa,  W_2_32, +W_1_32); pc++; pa += 1;
				XMAC(pc, pa,  W_1_32, +W_2_32); pc++; pa += 1;
				XMAC(pc, pa,  W_0_32, +W_3_32); pc++; pa += 1;
			case 4:
				XMAC(pc, pa,  W_0_16, -W_1_16); pc++; pa += 1;
				XMAC(pc, pa,  W_1_16, -W_0_16); pc++; pa += 1;
				XMAC(pc, pa, -W_1_16, -W_0_16); pc++; pa += 1;
				XMAC(pc, pa, -W_0_16, -W_1_16); pc++; pa += 1;
				pa -= 4;
				XMAC(pc, pa, -W_0_16, +W_1_16); pc++; pa += 1;
				XMAC(pc, pa, -W_1_16, +W_0_16); pc++; pa += 1;
				XMAC(pc, pa,  W_1_16, +W_0_16); pc++; pa += 1;
				XMAC(pc, pa,  W_0_16, +W_1_16); pc++; pa += 1;
			case 3:
				XMAC(pc, pa,  W_0_08, -W_0_08); pc++; pa += 1;
				XMAC(pc, pa, -W_0_08, -W_0_08); pc++; pa += 1;
				pa -= 2;
				XMAC(pc, pa, -W_0_08, +W_0_08); pc++; pa += 1;
				XMAC(pc, pa,  W_0_08, +W_0_08); pc++; pa += 1;
			case 2:
				XMAC(pc, pa, -W_0_04, -W_0_02); pc++; pa += 1;
				pa -= 1;
				XMAC(pc, pa,  W_0_04, +W_0_02); pc++; pa += 1;
			case 1:
				XMAC(pc, pa, -W_0_02, +W_0_04); pc++; pa += 1;
				pa -= 1;
			case 0:
				XMAC(pc, pa,  W_0_02, +W_0_04); pc++; pa += 1;
			}
		}
	}
	for (i = 0; i < (1 << LN_FFT); i++) {
		data[2*i+1] = pOut[OutOrder[i]].r;
		data[2*i+2] = pOut[OutOrder[i]].i;
	}
}
